# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 莫大艺术家

description: > # this means to ignore newlines until "baseurl:"
    吃饭是一门艺术，睡觉是一门艺术。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://igaves.com" # the base hostname & protocol for your site
#twitter_username: igaves
#github_username:  jekyll

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

paginate : 20